FROM rocker/tidyverse:3.6.3-ubuntu18.04

RUN apt-get update -y && apt-get install -y  \
    unixodbc \
    unixodbc-dev \
    tdsodbc \
    freetds-bin \
    freetds-dev \
    odbc-postgresql \
    tzdata

RUN apt-get install -y curl gnupg2

# See about installing ODBC drivers here: https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017
# Note that the driver version installed needs to match the version used in the code
# In this case for Ubuntu 18.04: ODBC SQL driver 17
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update -y
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev mssql-tools


COPY odbc/* /etc/
# Permissions are such that works fine as root but not from RStudio where user is not root
# so MUST do the following else an unhelpful error message tells you the file does not exist
RUN chmod a+rw /etc/odbc.ini && chmod a+rw /etc/odbcinst.ini


# https://www.rocker-project.org/use/extending/
# install core libraries
RUN install2.r odbc renv

# this is necessary for the rstudio instance to work
COPY .Renviron /home/rstudio

# this allows installation from the commandline
ENV http_proxy="http://www-cache-n.xuclh.nhs.uk:3128/"
ENV https_proxy="http://www-cache-n.xuclh.nhs.uk:3128/"
ENV HTTP_PROXY="http://www-cache-n.xuclh.nhs.uk:3128/"
ENV HTTPS_PROXY="http://www-cache-n.xuclh.nhs.uk:3128/"

ENV UID=$UID

