# Pull your base docker image
# Using rocker for R but could use python:3.8-slim or similar
FROM rocker/tidyverse:4.0.4

# Remove root privileges from the container process and run as 'cronbot'
RUN groupadd --gid 1001 cronbot && \
    useradd --uid 1001 --gid 1001 --create-home --shell /bin/bash cronbot

# install necessary packages for connecting from R to SQL databases
RUN apt-get update -y && apt-get install -y \
    unixodbc \
    unixodbc-dev \
    tdsodbc \
    odbc-postgresql \
    tzdata

# Copy the odbc configuration files onto the image
COPY odbc/* /etc/

# Install necessary libraries and R set-up
# Do separately to the app installation so that unless you change the necessary
# libraries you can debug end edit the app without rebuilding the full image
COPY app/setup.R /home/cronbot/setup.R
RUN Rscript /home/cronbot/setup.R

# Now copy supporting files in app to the image
COPY app/app /home/cronbot/app
# Now copy the main file 'app.R'
COPY app/app.R /home/cronbot/

# Ensure all files are owned by the user cronbot
RUN chown -R "1001:1001" /home/cronbot
USER cronbot

WORKDIR /home/cronbot

# Start the container with a 'dummy' process that prevents the container
# immediately stopping
CMD tail -f /dev/null





